### ISSUE TITLE
To agree routing system

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Software-Design#25]
Let us establish which URL opens which page

**Comment by iamprovidence** [comment]
I propose next urls

* main

|   URL     |      Page      |
|:---------:|-------------:|
|  \           | registration |

* administrator

|            URL                         |                   Page                   |
|:-----------------------------|-------------------------------:|
|  administrator\                  |    index                                 |
|  administrator\\page=2 \ |    index on current page       |

**Comment by Lenkelheit** [comment]
> I propose next urls
> 
> * main
> 
> URL	Page
> \	registration
> * administrator
> 
> URL	Page
> administrator\	index
> administrator\page=2 \	index on current page

Agree with you.
