### ISSUE TITLE
Use-case diagram

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Software-Design#5]

**Comment by iamprovidence** [comment]
![General use case diagram](https://user-images.githubusercontent.com/24938726/54436078-8b2a6f00-473a-11e9-9bed-213334f74f59.png)

**Comment by Lenkelheit** [comment]
Bad transparent background:
![image](https://user-images.githubusercontent.com/38116562/54464662-3873a600-4780-11e9-8d8d-111d1766ece6.png)

**Comment by iamprovidence** [comment]
@Lenkelheit , it does not matter. this picture will be on white background
